# Practice

In [390]:
import numpy as np
import pandas as pd
rng = np.random.default_rng(23)

## numpy practice 

Only use np library for this practice.

1. Create two np arrays: $\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$ and $\begin{bmatrix} 1 & 4 & 7 \\ 2 & 5 & 8 \\ 3 & 6 & 9 \end{bmatrix}$. Do not create the arrays by listing all the elements.

In [391]:
#Make an array between numbers 1 to 9 and reshape it to put that number in the matrix. 
arr = np.arange(1,10).reshape((3, 3)) 
#change the matrix number row to column 
arr2 = arr.T

print(arr)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


2. Compute row-wise means and standard deviations of the generated arrays.

In [392]:
arr = np.arange(1,10).reshape((3, 3)) 
arr2 = arr.T

#function for finding the mean of row-wise numbers, "1" meaning is select the row 
def arr_mean():
    mean_1 = np.mean(arr, axis = 1)
    mean_2 = np.mean(arr2, axis = 1)
    print(mean_1)
    print(mean_2)
    
#function for finding the standard deviations of row-wise numbers, "1" meaning is select the row 
def arr_std():
    std_1 = np.std(arr, axis =1)
    std_2 = np.std(arr2, axis = 1)
    print(std_1)
    print(std_2)
    
arr_mean()
arr_std()



[2. 5. 8.]
[4. 5. 6.]
[0.81649658 0.81649658 0.81649658]
[2.44948974 2.44948974 2.44948974]


3. Compute column-wise means and standard deviations of the generated arrays.

In [393]:
arr = np.arange(1,10).reshape((3, 3)) 
arr2 = arr.T

#function for finding the mean of column-wise numbers, "0" meaning is select the column
def arr_mean():
    mean_1 = np.mean(arr, axis = 0)
    mean_2 = np.mean(arr2, axis = 0)
    print(mean_1)
    print(mean_2)

#function for finding the standard deviations of column-wise numbers, "0" meaning is select the column
def arr_std():
    std_1 = np.std(arr, axis = 0)
    std_2 = np.std(arr2, axis = 0)
    print(std_1)
    print(std_2)

arr_mean()
arr_std()

[4. 5. 6.]
[2. 5. 8.]
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


4. Create 10 by 10 np array where each element is sampled from the normal distribution with mean 0 and standard deviation 5. Print the generated array.

In [394]:

def t_arr(): 
    rng = np.random.default_rng(100) #make random number
    t_normal = np.random.normal(0,5,100) #calculate random numbers' normal distribution with mean 0 and standard deviation 5.
    result = t_normal.reshape((10,10)) #put the result of calculation in matrix 
    print(result)
   
    
t_arr()

[[ -1.51837404  -3.89049642   0.92178664  -2.70387915 -14.78952981
   -7.95840597   3.87298577  -5.74619842  -1.73008928  -2.79784409]
 [ -4.00298118  -0.605201     0.48082498   0.6355453   -1.63517161
   -1.21491778   5.9270643   14.11913797  -2.1362682    3.93027902]
 [ -2.13821451   3.45452932  -9.63442252   6.38032406   7.59050897
    4.75588478  -4.63419031  -0.35284689  -4.66376581  -3.91752443]
 [  3.63315267  -4.07523831  -4.83747946  -0.40783316   0.24471516
    3.67124694   5.99109205   0.92149505   3.83159425   4.83545873]
 [  3.66857722   7.68083845   1.5948642   -2.30269367  -6.38375339
   -4.05231708  -2.75448971   7.83801961  -3.21919062  -3.57469587]
 [ -0.36563657  -0.82908196   4.84667446   0.95176043  -2.80758333
   -2.32131555  -1.9633852    3.25103426   4.19622327   4.82777024]
 [  3.4564478   -0.89248355   1.76683172  -3.1348311   -2.87063734
   -6.20485851  -6.59278083  -1.70488354   4.03676537   6.50409726]
 [ -2.02054092  -1.47172899  -1.354357     2.80608809  

5. Write a function that uses inputs of (array, axis) and returns: 


* If the axis is 0, returns the column-wise standardized array (for each column, mean is 0 and standard deviation is 1) 
* If the axis is 1, returns the row-wise standardized array (for each row, mean is 0 and standard deviation is 1) 
* If the axis is not 0 nor 1, then print the error message 

Test the function with the arrays created in Q1. If the outputs are correct, compute the row-wise and column-wise means and standard devations of the array generated in Q4.

In [395]:
def t_arr(): 
    rng = np.random.default_rng(100)
    t_normal = np.random.normal(0,5,100)
    result = t_normal.reshape((10,10))
    return result 

arr_result = t_arr() #call the function in arr_result to easy to use in next function

def logic_in(arrx,ax):
    
    #build the logic to distinguish the axis column 
    if ax == 0:
        #calculate mean and standard deviations for building a standardized formula 
        arr_m = np.mean(arr_result, axis = 0) 
        std_dev = np.std(arr_result, axis=0)
        s_array = (arr_result - arr_m) / std_dev
        return s_array
    #build the logic to distinguish the axis row
    elif ax == 1:
        #calculate mean and standard deviations for building a standardized formula 
        arr_m2 = np.mean(arr_result, axis = 1) 
        std_dev2 = np.std(arr_result, axis=1)
        s_array2 = (arr_result - arr_m2) / std_dev2
        return s_array2
    #build the logic for error 
    else:
        print("value is error")
    
    
print(logic_in(arr_result,0))
print(logic_in(arr_result,1))




[[-8.62793999e-01 -1.58529515e+00 -9.37228308e-02 -1.55416190e+00
  -8.69774188e-01 -1.39455210e+00 -1.96880718e-01  1.61128415e-01
  -1.46013661e+00  8.69667280e-01]
 [-5.79695751e-01 -1.18133194e+00  1.08956984e+00 -9.47762512e-02
  -1.17245659e-01  7.16443819e-01  6.49286685e-02 -1.02850055e+00
   8.69600648e-01 -7.90686811e-02]
 [-1.44473147e+00  8.89396209e-02 -6.99202018e-02  5.45415902e-02
   1.19982825e-01  4.95408465e-01  1.64266123e+00  1.02135604e+00
   9.58065948e-01 -8.84840441e-01]
 [ 1.51301456e+00  9.69161934e-01 -1.21092809e+00  2.20788077e+00
   1.70067746e+00 -3.79541226e-02  1.15724797e+00 -1.88226612e+00
   1.58515600e+00 -2.16106419e+00]
 [ 1.11251391e+00  1.58029606e+00  1.50752633e+00 -9.34504376e-01
  -1.06059310e+00  1.67394710e+00  4.88908821e-01 -8.40686440e-01
  -3.15796284e-01  8.89582915e-02]
 [ 8.00886535e-01  3.10989719e-01 -1.81236542e+00  5.81346038e-01
  -7.34160437e-01 -2.03118129e-03 -1.99604549e+00  1.45950527e+00
  -1.88034879e+00  1.40835904e+00

## pandas practice 

We will use the wine quality data (https://archive.ics.uci.edu/ml/datasets/Wine+Quality). Only use pd library for this practice.

6. Load winequality-red.csv as data frame using pd and save it as winequality_red

In [396]:
# Read CSV file using Panda 
winequality_red = pd.read_csv('C:/Users/choih/OneDrive/Desktop/r_wine.csv', sep=';')
print(winequality_red)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  

7. Use head and info functions to check the information of winequality_red. Briefly summarize the information of the imported dataset.

In [397]:
#check and summarize the information from the dataset.
winequality_red.head()
winequality_red.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


8. We want to find the high-quality low-alcohol wines. Show information of wines whose alcohol is less than 10 and quality is greater than or equal to 7. How many wines are there that meet?

In [398]:
#filter out with the given conditions 
goodwine = winequality_red[(winequality_red.alcohol < 10) & (winequality_red.quality >= 7)]

#print out the selected wines
goodwine.info()
#print out a number of selected wines 
print("Total selected wines: " + str(len(goodwine.columns)))

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 8 to 1089
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         12 non-null     float64
 1   volatile acidity      12 non-null     float64
 2   citric acid           12 non-null     float64
 3   residual sugar        12 non-null     float64
 4   chlorides             12 non-null     float64
 5   free sulfur dioxide   12 non-null     float64
 6   total sulfur dioxide  12 non-null     float64
 7   density               12 non-null     float64
 8   pH                    12 non-null     float64
 9   sulphates             12 non-null     float64
 10  alcohol               12 non-null     float64
 11  quality               12 non-null     int64  
dtypes: float64(11), int64(1)
memory usage: 1.2 KB
Total selected wines: 12


## string practice 

9. We have the following product descriptions.

Write the function(s) that can retrieve the three numbers of size (height, width, and depth) in all product descriptions. In some product descriptions, the orders of height, width, and depth could be different. However, we know that the product dimension would always be in the following order: height>width>depth. Test the function(s) using the given product descriptions.

In [399]:
#for using regular expressions 
import re

rucksack1 = "Rucksack. Leather and polyester. Dimensions: 18'' tall x 12'' wide x 5'' deep. Brown or black."
rucksack2 = "Classic Leather Backpack for Man. Dim: height 18'' & width 16'' & depth 8''."
rucksack3 = "Multi-purpose clear backpack. Size: 15.8 by 12.9 by 8.4 (inch)."
rucksack4 = "16(W)x18.4(H)x4.5(D)"

#To find out only numbers from sentence 
def f_num(rucksack):
    numbers = re.findall(r'\d+\.\d+|\d+', rucksack)
    digits = []
    for n in numbers:
        try:
            n = float(n)
            digits.append(n) 
        except ValueError:
            continue
    
    return digits

#Make a function that prints out the number by conditions
def result(rucksack):
    result_s = f_num(rucksack) #bring a previous functions   
    #To find out patterns by condition
    height_pattern = r'(height|tall)[\s:]*([\d\.]+)\'\'|(\d+\.\d+)'  
    width_pattern = r'(width|wide)[\s:]*([\d\.]+)\'\'|(\d+\.\d+)'   
    depth_pattern = r'(depth|deep)[\s:]*([\d\.]+)\'\'|(\d+\.\d+)'   
    
    #to search specific pattern by condition 
    height_match = re.search(height_pattern, rucksack, re.IGNORECASE)
    width_match = re.search(width_pattern, rucksack, re.IGNORECASE)
    depth_match = re.search(depth_pattern, rucksack, re.IGNORECASE)

    #If it matchs object for the string "height 18" then "height_match.group(2)" will extract the number else it will be None
    # width and depth also same logic 
    height = height_match.group(2) if height_match else None
    width = width_match.group(2) if width_match else None
    depth = depth_match.group(2) if depth_match else None
    
    # This checks whether none of the height, width, or depth values have been assigned a valid value.
    if not height and not width and not depth:
        if len(result_s) >= 3:
            height, width, depth = result_s[:3]
    
    return height, width, depth
    
print(result(rucksack1))
print(result(rucksack2))
print(result(rucksack3))
print(result(rucksack4))


(18.0, 12.0, 5.0)
('18', '16', '8')
(15.8, 12.9, 8.4)
(16.0, 18.4, 4.5)
